// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cleanup(arg1, arg2) {
  return window['go']['main']['App']['Cleanup'](arg1, arg2);
}

export function GetPartitions() {
  return window['go']['main']['App']['GetPartitions']();
}

export function GetProgress() {
  return window['go']['main']['App']['GetProgress']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Reboot() {
  return window['go']['main']['App']['Reboot']();
}

export function SelectISO() {
  return window['go']['main']['App']['SelectISO']();
}

export function StartInstallation(arg1) {
  return window['go']['main']['App']['StartInstallation'](arg1);
}

export function ValidateISO(arg1) {
  return window['go']['main']['App']['ValidateISO'](arg1);
}
