// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {disk} from '../models';
import {main} from '../models';
import {iso} from '../models';

export function Cleanup(arg1:string,arg2:string):Promise<void>;

export function GetPartitions():Promise<Array<disk.Partition>>;

export function GetProgress():Promise<main.Progress>;

export function Greet(arg1:string):Promise<string>;

export function Reboot():Promise<void>;

export function SelectISO():Promise<string>;

export function StartInstallation(arg1:main.InstallRequest):Promise<void>;

export function ValidateISO(arg1:string):Promise<iso.Info>;
